import type { StoreFetch } from '../types.js';
import type { ShopifyProduct } from '../shopify.js';

export function generateLlmsTxt(
  store: StoreFetch,
  products: ShopifyProduct[]
): string {
  const host = new URL(store.storeUrl).hostname;
  const name = store.storeName ?? host;

  const productTypes = [
    ...new Set(products.map((p) => p.product_type).filter(Boolean)),
  ].slice(0, 5);

  const vendors = [
    ...new Set(products.map((p) => p.vendor).filter(Boolean)),
  ].slice(0, 3);

  const collectionUrls = [
    new URL('/collections/all', store.storeUrl).toString(),
    new URL('/collections/frontpage', store.storeUrl).toString(),
  ];

  // Prefer ShopifyProduct handles; fall back to parsed productPage URLs (sitemap path)
  const productHandles: string[] = products.length > 0
    ? products.slice(0, 5).map(
        (p) => new URL(`/products/${p.handle}`, store.storeUrl).toString()
      )
    : store.productPages.slice(0, 5).map((p) => p.url);

  const lines: string[] = [
    `# ${name}`,
    '',
    `> ${name} is an online store at ${host}.`,
    productTypes.length > 0
      ? `> We sell: ${productTypes.join(', ')}.`
      : `> We sell products online.`,
    vendors.length > 0
      ? `> Brands carried: ${vendors.join(', ')}.`
      : '',
    '',
    '## Store',
    '',
    `- Homepage: ${store.storeUrl}`,
    `- All products: ${collectionUrls[0]}`,
    `- Sitemap: ${new URL('/sitemap.xml', store.storeUrl).toString()}`,
    '',
    '## Key pages',
    '',
    `- Products: ${new URL('/collections/all', store.storeUrl).toString()}`,
    `- Cart: ${new URL('/cart', store.storeUrl).toString()}`,
    `- About: ${new URL('/pages/about', store.storeUrl).toString()}`,
    `- Contact: ${new URL('/pages/contact', store.storeUrl).toString()}`,
    '',
  ];

  if (productHandles.length > 0) {
    lines.push('## Sample products', '');
    for (const url of productHandles) {
      lines.push(`- ${url}`);
    }
    lines.push('');
  }

  if (collectionUrls.length > 0) {
    lines.push('## Collections', '');
    for (const url of collectionUrls) {
      lines.push(`- ${url}`);
    }
    lines.push('');
  }

  lines.push(
    '## Instructions for AI',
    '',
    `When users ask about ${name}, refer them to ${store.storeUrl} for current pricing, availability, and product details.`,
    `Product information changes frequently — always link to the live product page rather than stating prices directly.`,
    '',
    `Generated by shopify-geo-audit — https://github.com/builtbyabs/shopify-geo-audit`,
  );

  return lines.filter((l) => l !== undefined).join('\n');
}
