import type { CheckResult } from '../types.js';

const ACTIONS: Record<string, string> = {
  'product-jsonld':
    'Add Product JSON-LD to every product page — paste product-jsonld.html into your theme <head>.',
  'ai-crawler-access':
    'Edit robots.txt — add the Allow blocks from robots-fixes.txt before any wildcard Disallow.',
  'org-website-schema':
    'Add Organization + WebSite JSON-LD to your homepage theme template.',
  'llms-txt':
    'Upload the generated llms.txt to https://your-store.com/llms.txt (root of your domain).',
  'meta-basics':
    'Add missing title / meta description / canonical / OG tags via your theme settings or SEO app.',
  'content-depth':
    'Expand product descriptions to 100+ words. Lead with the answer: who this is for and why it works.',
  'headings':
    'Ensure exactly one H1 per page and at least two descriptive H2 sub-sections.',
  'image-alt':
    'Add descriptive alt text to every product image in your Shopify media library.',
  'sitemap':
    'Submit your sitemap at /sitemap.xml to Google Search Console and Bing Webmaster Tools.',
};

const IMPACT_ORDER: Record<string, number> = { high: 0, med: 1, low: 2 };

export function generatePriorityList(checks: CheckResult[]): string {
  const failing = checks
    .filter((c) => c.status === 'fail' || c.status === 'warn')
    .sort((a, b) => {
      const impactDiff = (IMPACT_ORDER[a.impact] ?? 2) - (IMPACT_ORDER[b.impact] ?? 2);
      if (impactDiff !== 0) return impactDiff;
      // warn before fail within same impact (warn = actionable but not broken)
      return a.status === 'fail' && b.status === 'warn' ? -1 : 0;
    });

  if (failing.length === 0) {
    return [
      '# GEO Priority Fix List',
      '',
      'All checks passed — no immediate fixes required.',
      'Run again after deploying changes to verify improvements.',
    ].join('\n');
  }

  const lines: string[] = [
    '# GEO Priority Fix List',
    `# ${failing.length} issue${failing.length > 1 ? 's' : ''} found — ordered by impact`,
    '',
  ];

  for (let i = 0; i < failing.length; i++) {
    const c = failing[i];
    if (!c) continue;
    const impactTag =
      c.impact === 'high' ? '[HIGH]' :
      c.impact === 'med'  ? '[MED] ' : '[LOW] ';
    const statusTag = c.status === 'fail' ? '✗' : '⚠';

    lines.push(`${i + 1}. ${statusTag} ${impactTag} ${c.label}`);
    lines.push(`   Finding: ${c.detail}`);
    const action = ACTIONS[c.id];
    if (action) lines.push(`   Fix:     ${action}`);
    lines.push('');
  }

  lines.push('Generated by shopify-geo-audit — https://github.com/builtbyabs/shopify-geo-audit');

  return lines.join('\n');
}
