import type { StoreFetch } from '../types.js';
import type { ShopifyProduct } from '../shopify.js';

function availability(product: ShopifyProduct): string {
  const variant = product.variants?.[0];
  if (!variant) return 'https://schema.org/InStock';
  return variant.available === false
    ? 'https://schema.org/OutOfStock'
    : 'https://schema.org/InStock';
}

function firstImage(product: ShopifyProduct, storeUrl: string): string | undefined {
  const img = product.images?.[0];
  if (!img) return undefined;
  if (/^https?:\/\//.test(img.src)) return img.src;
  return new URL(img.src, storeUrl).toString();
}

export function generateProductJsonLd(
  product: ShopifyProduct,
  storeUrl: string
): string {
  const variant = product.variants?.[0];
  const price = variant?.price ?? '0.00';
  const sku = variant?.sku ?? undefined;
  const image = firstImage(product, storeUrl);

  const schema: Record<string, unknown> = {
    '@context': 'https://schema.org',
    '@type': 'Product',
    name: product.title,
    description: product.body_html
      ? product.body_html.replace(/<[^>]+>/g, ' ').replace(/\s+/g, ' ').trim()
      : undefined,
    url: new URL(`/products/${product.handle}`, storeUrl).toString(),
    offers: {
      '@type': 'Offer',
      price,
      priceCurrency: 'USD',
      availability: availability(product),
      url: new URL(`/products/${product.handle}`, storeUrl).toString(),
    },
  };

  if (image) schema['image'] = image;
  if (sku) schema['sku'] = sku;
  if (product.vendor) {
    schema['brand'] = { '@type': 'Brand', name: product.vendor };
  }

  // Never emit AggregateRating — we have no genuine review data from a public fetch.
  // Merchants should add this from their own review platform data.

  const json = JSON.stringify(schema, null, 2);
  return `<script type="application/ld+json">\n${json}\n</script>`;
}

export function generateProductJsonLdFix(
  products: ShopifyProduct[],
  store: StoreFetch
): string {
  if (products.length === 0) {
    return '<!-- No products found via /products.json — fetch product data and apply this template:\n'
      + generateProductJsonLd(
          {
            id: 0,
            title: 'Your Product Name',
            handle: 'your-product-handle',
            body_html: 'Your product description here.',
            vendor: 'Your Brand',
            images: [{ src: 'https://your-store.com/product-image.jpg', alt: null }],
            variants: [{ price: '0.00', available: true, sku: null, compare_at_price: null }],
          },
          store.storeUrl
        )
      + '\n-->';
  }

  const lines: string[] = [
    '<!--',
    '  Product JSON-LD — generated by shopify-geo-audit',
    `  Add ONE of these blocks to the <head> of each product page template.`,
    '  In Shopify: Online Store → Themes → Edit Code → product.json or theme.liquid',
    '-->',
    '',
  ];

  for (const product of products.slice(0, 3)) {
    lines.push(`<!-- /products/${product.handle} -->`);
    lines.push(generateProductJsonLd(product, store.storeUrl));
    lines.push('');
  }

  if (products.length > 3) {
    lines.push(
      `<!-- ${products.length - 3} more products — apply the same pattern with Shopify Liquid: -->`,
      '',
      `<!-- Liquid template version (paste into product.liquid <head>): -->`,
      `<script type="application/ld+json">`,
      `{`,
      `  "@context": "https://schema.org",`,
      `  "@type": "Product",`,
      `  "name": {{ product.title | json }},`,
      `  "description": {{ product.description | strip_html | json }},`,
      `  "image": {{ product.featured_image | img_url: 'master' | prepend: 'https:' | json }},`,
      `  "offers": {`,
      `    "@type": "Offer",`,
      `    "price": {{ product.price | money_without_currency | json }},`,
      `    "priceCurrency": {{ cart.currency.iso_code | json }},`,
      `    "availability": {% if product.available %}"https://schema.org/InStock"{% else %}"https://schema.org/OutOfStock"{% endif %},`,
      `    "url": {{ shop.url | append: product.url | json }}`,
      `  },`,
      `  "brand": { "@type": "Brand", "name": {{ product.vendor | json }} }`,
      `}`,
      `</script>`,
    );
  }

  return lines.join('\n');
}
