import type { AuditResults, CheckResult } from '../types.js';
import { EMBEDDED_FONT_CSS } from './fonts.js';
import { REPORT_CSS } from './styles.js';

function esc(raw: string): string {
  return raw
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

function statusIcon(status: CheckResult['status']): string {
  if (status === 'pass') return '✓';
  if (status === 'warn') return '⚠';
  return '✗';
}

function statusClass(status: CheckResult['status']): string {
  if (status === 'pass') return 'pass';
  if (status === 'warn') return 'warn';
  return 'fail';
}

function impactBadge(impact: CheckResult['impact']): string {
  const label = impact.toUpperCase();
  return `<span class="badge badge-${impact}">${label}</span>`;
}

function checkRow(c: CheckResult): string {
  const cls = statusClass(c.status);
  const icon = statusIcon(c.status);
  return `
  <div class="check-row ${cls}">
    <span class="check-icon">${icon}</span>
    <div class="check-body">
      <div class="check-label">
        ${esc(c.label)}
        ${impactBadge(c.impact)}
      </div>
      ${c.status !== 'pass' ? `<div class="check-detail">${esc(c.detail)}</div>` : ''}
    </div>
  </div>`;
}

export function generateHtmlReport(results: AuditResults): string {
  const { checks, score, storeUrl, storeName, generatedAt } = results;

  const impactOrder: Record<string, number> = { high: 0, med: 1, low: 2 };
  const statusOrder: Record<string, number> = { fail: 0, warn: 1, pass: 2 };
  const sorted = [...checks].sort((a, b) => {
    const sd = (statusOrder[a.status] ?? 2) - (statusOrder[b.status] ?? 2);
    if (sd !== 0) return sd;
    return (impactOrder[a.impact] ?? 2) - (impactOrder[b.impact] ?? 2);
  });

  const checkRows = sorted.map(checkRow).join('');
  const failing   = checks.filter((c) => c.status === 'fail').length;
  const warnings  = checks.filter((c) => c.status === 'warn').length;
  const passing   = checks.filter((c) => c.status === 'pass').length;
  const displayName = esc(storeName ?? storeUrl);
  const safeUrl = esc(storeUrl);
  const bandClass = score.band === 'Strong' ? 'strong' :
                    score.band === 'Needs work' ? 'needs-work' : 'at-risk';

  const faqSchema = JSON.stringify({
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: [
      {
        '@type': 'Question',
        name: 'What is a GEO audit for Shopify?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'A GEO (Generative Engine Optimization) audit checks whether your Shopify store has the structured data, content signals, and crawl permissions that AI search engines — like ChatGPT, Perplexity, and Google AI Overviews — need to discover, understand, and cite your products.',
        },
      },
      {
        '@type': 'Question',
        name: 'What is an SRO Score?',
        acceptedAnswer: {
          '@type': 'Answer',
          text: 'SRO stands for Search Readiness for AI. It is a 0–100 score that measures how well your store signals are optimized for AI search engines. Scores of 80+ are Strong; 50–79 Need work; below 50 are At risk of being invisible to AI assistants.',
        },
      },
    ],
  }, null, 2);

  const softwareSchema = JSON.stringify({
    '@context': 'https://schema.org',
    '@type': 'SoftwareApplication',
    name: 'shopify-geo-audit',
    applicationCategory: 'DeveloperApplication',
    operatingSystem: 'macOS, Linux, Windows',
    description: 'Zero-config CLI that audits any Shopify storefront for AI-search readiness and generates paste-ready fixes.',
    offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' },
    url: 'https://github.com/Abs-Automation/shopify-geo-audit',
  }, null, 2);

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>GEO Audit — ${displayName}</title>
<meta name="description" content="AI-search readiness audit for ${displayName}. SRO Score: ${score.value}/100. Generated by shopify-geo-audit.">
<script type="application/ld+json">${faqSchema}</script>
<script type="application/ld+json">${softwareSchema}</script>
<style>
/* ─── Fonts — Archivo Black (display) + IBM Plex Mono (body/code), embedded inline (offline-safe) ─── */
${EMBEDDED_FONT_CSS}

${REPORT_CSS}
</style>
</head>
<body>
<div class="wrap">

  <header>
    <div class="header-inner">
      <div>
        <div class="brand">shopify-geo-audit</div>
        <div class="store-name">${displayName}</div>
        <div class="store-url">${safeUrl}</div>
      </div>
      <div class="timestamp">Generated<br>${generatedAt}</div>
    </div>
  </header>

  <div class="score-block">
    <div class="score-label">SRO Score — Search Readiness for AI</div>
    <div class="score-display">
      <span class="score-number ${bandClass}" id="score-num">${score.value}</span>
      <span class="score-denom">/ 100</span>
      <span class="score-band ${bandClass}" id="score-band">${score.band.toUpperCase()}</span>
    </div>
    <div class="stats">
      <div class="stat">
        <span class="stat-num fail-color">${failing}</span>
        <span class="stat-lbl">Failing</span>
      </div>
      <div class="stat">
        <span class="stat-num warn-color">${warnings}</span>
        <span class="stat-lbl">Warnings</span>
      </div>
      <div class="stat">
        <span class="stat-num pass-color">${passing}</span>
        <span class="stat-lbl">Passing</span>
      </div>
    </div>
  </div>

  <section>
    <div class="section-label">Audit results — ${checks.length} checks</div>
    <div class="checks" id="checks">
      ${checkRows}
    </div>
  </section>

  <section>
    <div class="section-label">Generated fixes</div>
    <div class="accent-bar"></div>
    <p style="color:var(--dim);font-size:0.8rem;line-height:1.7;">
      Files written to <code style="color:var(--accent)">./geo-audit-output/</code>:
    </p>
    <ul style="margin-top:16px;list-style:none;display:flex;flex-direction:column;gap:10px;">
      <li style="font-size:0.8rem;"><span style="color:var(--accent)">→</span>&nbsp; <strong>product-jsonld.html</strong> — paste-ready Product JSON-LD blocks for your theme</li>
      <li style="font-size:0.8rem;"><span style="color:var(--accent)">→</span>&nbsp; <strong>llms.txt</strong> — content manifest for AI crawlers, upload to your domain root</li>
      <li style="font-size:0.8rem;"><span style="color:var(--accent)">→</span>&nbsp; <strong>robots-fixes.txt</strong> — exact robots.txt lines to unblock AI crawlers</li>
      <li style="font-size:0.8rem;"><span style="color:var(--accent)">→</span>&nbsp; <strong>priority-list.txt</strong> — all issues ranked by impact, each with one-line fix</li>
    </ul>
  </section>

  <footer>
    <span class="footer-brand">shopify-geo-audit</span>
    <a class="footer-link" href="https://github.com/Abs-Automation/shopify-geo-audit" target="_blank" rel="noopener">
      github.com/Abs-Automation/shopify-geo-audit
    </a>
  </footer>

</div>

<!-- GSAP — score reveal + check stagger -->
<script
  src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.12.5/gsap.min.js"
  integrity="sha512-7eHRwcbYkK4d9g/6tD/mhkf++eoTHwpNM9woBxtPUBWm67zeAfFC+HrdoE2GanKeocly/VxeLvIqwvCdk7qScg=="
  crossorigin="anonymous"
  referrerpolicy="no-referrer"></script>
<script>
(function () {
  // Progressive enhancement: if GSAP didn't load (e.g. offline), content is
  // already fully visible via CSS — we just skip the animation.
  if (!window.gsap) return;

  const scoreEl = document.getElementById('score-num');
  const bandEl  = document.getElementById('score-band');
  const rows    = document.querySelectorAll('.check-row');
  const target  = parseInt(scoreEl.textContent, 10);

  const tl = gsap.timeline({ defaults: { ease: 'power3.out' } });

  // Score number count-up from 0
  const counter = { val: 0 };
  scoreEl.textContent = '0';
  tl.from(scoreEl, { opacity: 0, duration: 0.3 }, 0);
  tl.to(counter, {
    val: target,
    duration: 1.2,
    ease: 'power2.out',
    onUpdate() { scoreEl.textContent = Math.round(counter.val); },
  }, 0);

  // Band + check rows reveal from hidden → their visible resting state
  tl.from(bandEl, { opacity: 0, duration: 0.3 }, 0.8);
  tl.from(rows, {
    y: 12,
    opacity: 0,
    stagger: 0.06,
    duration: 0.35,
    ease: 'power2.out',
  }, 0.5);
})();
</script>
</body>
</html>`;
}
